``` 
# Dockerfile
FROM ubuntu:22.04 # базовый образ ubuntu
LABEL description="Build nginx" # description
VOLUME /var/log/nginx/ #подключение внешнего тома для записи логов на хостовую машину
RUN apt update  && apt install nginx -y #установка  nginx в контейнер
COPY nginx.conf /etc/nginx # копировать с хостовой машины конфиг-файл для nginx
ENTRYPOINT ["nginx", "-g", "daemon off;"] #  команда для запуска контейнера

```
